### ISSUE TITLE
Can't separate by newline

### ISSUE THREAD

**Issue by alphapapa** [dejbug/ff-tab-lister#1]
This looks like a very simple yet very useful extension.  I don't know how many times I've wanted to simply copy a list of open tab URLs to the clipboard, but for some reason it's not built into Firefox or even Tab Mix Plus.

But what I want is a simple, newline-separated list of URLs (and maybe titles).  But that's not possible.  I even put "\n" into the box but it comes out as a literal "\n".  D:

**Comment by dejbug** [comment]
hello alphapapa!

that's curious. if you clear the box down to a simple `{URL}` it should be generating the list. (the addon always creates a newline-separated list and the box holds the template for each row.)

but as to the `\n` literal, I'm so sorry! a simple `\n` won't do but a `\r\n` should. I will fix that shortly. good catch! :) in fact, i'll change it so that the `\n` at the end of the box won't be implied. this way it'll be up to the user whether they want a list or a single line of output, which makes much more sense anyway. (thanks again!)

please do tell me whether this resolves your issue! cheers!

p.s.: yes, that is strange that firefox wouldn't have this functionality integrated (considering that they pretty much have this addon as a hello world example in the [addon dev tutorial](https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/List_Open_Tabs)!)

**Comment by alphapapa** [comment]
Hey, thanks for your quick reply.  Actually I did `{URL} {TITLE}\n`.  It wouldn't hurt to just have a checkbox in the config to put each entry on a separate line... ;)  Oh, and then there's Windows CR/LF vs. Unix LF...

**Comment by dejbug** [comment]
yep, that's true with the new-line flavors. :) both `\r`and `\n` should now be handled correctly though.

the suggestion with the checkbox sounds good (in many respects), but i think i'm going to stick with simplicity. and your initial instincts on how the box was supposed to work were indeed correct. the real problem was merely the lack of documentation and, of course, the buggy handling of escapes. (also the implicit unix-style newline appended to the pattern in the box.)

all of this should be working fine now.

till the next time! all the best! ;)
